New model for resource usage optimisation in RCPSP problem
airbus/discrete-optimization pull request #45
Opened 2022-09-20 08:19 UTC by g-poveda

-  new model for resource usage optimisation
-  include a new parameters to params CP (optimisation_level) passed to minizinc solver in the generic minizinc solve function.

2022-09-22 14:01 UTC, nhuet requested changes
I do not have the skills to comment the new minizinc model.
Except for the change to make to the `copy` method, nothing mandatory.
Still an example (or better tests) would be nice to see in action these changes. Currently these new functions are used nowhere.

2022-10-06 12:55 UTC, g-poveda commented on discrete_optimization/rcpsp/minizinc/rcpsp_single_mode_mzn.mzn
changing log output (less verbose, notably for big rcpsp instance.

2022-10-11 10:05 UTC, g-poveda commented on discrete_optimization/generic_tools/cp_tools.py
> +    optimisation_level: int
done in 2a3dbd8f886c72accec4049a6bf6001942af10ef

2022-10-11 10:07 UTC, g-poveda commented on discrete_optimization/rcpsp/minizinc/rcpsp_multi_mode_resource_feasibility_mzn.mzn
parameter non hard coded anymore : https://github.com/airbus/discrete-optimization/pull/45/commits/cd6980756249cef30d70c7bf1837a4d0f8ecc88f

2022-10-11 10:07 UTC, g-poveda commented on discrete_optimization/generic_tools/cp_tools.py
>          logger.debug(result.status)
testing all available values in https://github.com/airbus/discrete-optimization/pull/45/commits/ff4b0bfe36414ef476546774c32320301f5e0b4f

2022-10-11 13:40 UTC, nhuet commented
LGTM once the workflow succeeds. (see my minor remark about minizinc model name [here](https://github.com/airbus/discrete-optimization/pull/45#discussion_r992336347).)

2022-10-11 19:14 UTC, g-poveda commented
Ok, tests finally passed with more timeout in solvers.

2022-10-11 19:14 UTC, merged